name: PR Update
run-name: Updating Issues on PR Close for ${{ github.base_ref }}

on:
  pull_request:
    branches:
      - develop
      - staging
    types: [closed]

jobs:
  merge_branches:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
        with:
          fetch-depth: 0

#Fix the Repo name

      - name: Add Labels to Issues
        run: |
          issues=$(gh api graphql -F owner='NoroGH' -F repo='testing_repo' -F pr=${{ github.event.pull_request.number }} -f query='
            query ($owner: String!, $repo: String!, $pr: Int!) {
              repository(owner: $owner, name: $repo) {
                pullRequest(number: $pr) {
                  closingIssuesReferences(first: 100) {
                    nodes {
                      number
                    }
                  }
                }
              }
            }'  --jq '.data.repository.pullRequest.closingIssuesReferences.nodes[].number')
          for issue in $issues; do
            gh issue edit $issue --add-label ${GITHUB_BASE_REF^}
          done
        env:
          GITHUB_TOKEN: ${{ secrets.GH_TOKEN }}
