name: PR Update
run-name: Updating Issues on PR Close for ${{ github.base_ref }}

on:
  pull_request:
    branches:
      - develop
      - staging
    types: [closed]

jobs:
  update-issues:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
        with:
          fetch-depth: 0
      - name: Add Staging Labels to Issues
        run: |
          echo "PR_BODY content:"
          echo "$PR_BODY"

          issues=$(echo "$PR_BODY" | grep -Eio '((close[sd]?|fix(e[sd]?|d)?|resolve[sd]?)\s+#([0-9]+))' | sed -E 's/.*#([0-9]+)/\1/')

          if [ -z "$issues" ]; then
            echo "No issues found in PR body."
            exit 0
          fi

          for issue in $issues; do
            echo "Adding label '${GITHUB_BASE_REF^}' to issue #$issue"
            gh issue edit "$issue" --add-label "${GITHUB_BASE_REF^}"
          done
        env:
          GITHUB_TOKEN: ${{ secrets.GH_TOKEN }}
          PR_BODY: ${{ github.event.pull_request.body }}
